### ISSUE TITLE
Not able to change inputsContainerStyles

### ISSUE THREAD

**Issue by ryanphung** [dsznajder/react-native-otp-inputs#11]
FEATURE REQUEST
---
Thanks for the very useful component.

It will be cool to have an option to change `inputsContainerStyles` which at the moment is defaulted to `{marginHorizontal: 25, marginVertical: 20}`. Sometimes we need to reset these margin while making our own styles.

I think it's a pretty simple fix - I could create PR for this if you're ok with that.

**Comment by dsznajder** [comment]
@ryanphung Published in `1.1.0`
