### ISSUE TITLE
Clear() method not working.

### ISSUE THREAD

**Issue by jaswalnisha** [dsznajder/react-native-otp-inputs#112]
Usage of Clear() methods is not clear i.e how to use the clear method? Thanks in advance

**Comment by dsznajder** [comment]
@jaswalnisha 	There is direct example in README.md how to use it. 
https://github.com/dsznajder/react-native-otp-inputs#methods

Please, look at it and give feedback if something, or what directly is unclear.

**Comment by jaswalnisha** [comment]
Thanks for feedback. I have tried the the way you have suggested, but it gives me the below error.
![Screen Shot 2019-08-28 at 6 41 23 PM](https://user-images.githubusercontent.com/41417012/63858709-9b21cc80-c9c3-11e9-90e4-86e40edeb81d.png)

**Comment by dsznajder** [comment]
@jaswalnisha Could you share a code, how you use this one?

**Comment by jaswalnisha** [comment]
export default class OTPScreen extends Component {
    otpRef = React.createRef()
    constructor(props) {
        super(props);
        this.state = {
            countDown: 5,
            otpCode:''
        }
    }


    componentDidMount(): void {
        this.clockCall = setInterval(() => {
            this.decrementClock();
        }, 1000);
    }

    decrementClock = () => {
        if (this.state.countDown === 0) {
            clearInterval(this.clockCall, this.setState({countDown: 0}));
        } else {
            this.setState((prevState) => ({countDown: prevState.countDown - 1}));
        }
    };

    componentWillUnmount() {
        clearInterval(this.interval);
    }

    onCodeEntered(code){
        let otp = '';
        otp = code + otp;
        this.setState({
            otpCode: otp
        });
    }

    clearOTP = () => {
        this.otpRef.current.clear()
    }

    onSubmitClick(){
        const {otpCode} = this.state
        if(otpCode.length !== 4){
            console.warn('enter valid code');
        }
        else{
            this.clearOTP()
            console.warn('valid code added.')
        }
    }

    onResendPress(){
        this.setState({
            countDown: 5
        })
        this.clockCall = setInterval(() => {
            this.decrementClock();
        }, 1000);
    }

    render() {
        const {countDown} = this.state;
        let second, minutes;
        if (countDown !== 0) {
            second = (`0${Math.floor(countDown) % 60}`).slice(-2);
            minutes = (`0${Math.floor(countDown / 60) % 60}`).slice(-2);
        }
        return (
            <SafeArea>
                <MainContainer>
                    <OTPView>
                        <OtpInputs
                            ref={this.otpRef}
                            handleChange={code => this.onCodeEntered(code)}
                            numberOfInputs={4}
                            inputContainerStyles={{
                                borderWidth: 2.5,
                                borderBottomWidth: 2.5,
                            }}
                            focusedBorderColor={"#9772c2"}
                            // unfocusedBorderColor={appColors.SAFE_AREA_COLOR}
                        />
                        <TimerView>
                            <TimerText>{countDown === 0 ? '00:00' : `${minutes}:${second}`}</TimerText>
                            <ResendOTPView disabled={countDown === 0 ? false : true}
                                           style={{opacity: countDown === 0 ? 1 : 0.5}} onPress={() => { this.onResendPress()
                            }}>
                                <ResendText>Resend OTP</ResendText>
                            </ResendOTPView>
                        </TimerView>
                    </OTPView>
                    <SubmitOTP onPress={() =>{this.onSubmitClick()}}>
                        <SubmitText>Submit</SubmitText>
                    </SubmitOTP>
                </MainContainer>
            </SafeArea>
        )
    }
}


I have used the otpRef in clearOTP(), which is being called in onSubmitPress().

**Comment by dsznajder** [comment]
@jaswalnisha which version you use?

**Comment by jaswalnisha** [comment]
React - 16.8.3,
React-Native - 0.59.4
Rreact-native-otp-inputs - ^3.3.2"

**Comment by dsznajder** [comment]
@jaswalnisha 	I'm very sorry! I was doing this feature lately and I did not correct the docs. The method is `reset`.

You should use it like:
```js
    this.otpRef.current.reset()
```

**Comment by jaswalnisha** [comment]
I worked.. Thank You
