### ISSUE TITLE
Key strokes on Android lost when pressed quickly

### ISSUE THREAD

**Issue by mohsinulhaq** [dsznajder/react-native-otp-inputs#115]
When I press the keys very quickly after one another, the keystrokes seem to get lost. Looks like if we input before the next input is focussed, it doesn't register. Any solution or workaround for this?
Thanks.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7688231/64068875-1a313200-cc5c-11e9-9208-f7f0bd2c9dd6.gif)
Here, I press 0 quickly twice, but I get it only once.

**Comment by dsznajder** [comment]
@mohsinulhaq Does this happenes on a real device?

**Comment by mohsinulhaq** [comment]
yes it does

**Comment by dsznajder** [comment]
@mohsinulhaq I need to take a look at it, but it's because otherwise you can't paste code into those :/

**Comment by dsznajder** [comment]
@mohsinulhaq checkout [v4](https://github.com/dsznajder/react-native-otp-inputs/releases/tag/v4.0.0-alpha.0). It's released now, with some changes related to android bugs.
