### ISSUE TITLE
Not able to set secure input

### ISSUE THREAD

**Issue by ryanphung** [dsznajder/react-native-otp-inputs#12]
FEATURE REQUEST
---
Thanks for the very useful component.

It will be very useful to have an option to set secure input, for example `<OtpInputs secure={true}/>`.

This is also a dead simple improvement - I could create PR for this if you're ok with that.

**Comment by dsznajder** [comment]
@ryanphung I've just published `1.1.0`v with `secureTextEntry`. Should resolve this one

**Comment by Susmitha-Bogala** [comment]
in my case secureTextEntry is not working?
