### ISSUE TITLE
Pasted OTP value cannot be edited

### ISSUE THREAD

**Issue by quanle1994** [dsznajder/react-native-otp-inputs#132]
Thank you for the component.
I encountered an issue with pasting value in the OTP. After pasting my OTP in the inputs, I cannot edit it. Below are the screenshots of the problem.

This is the pasted value.
![image](https://user-images.githubusercontent.com/17548904/65654090-369d7000-e04a-11e9-8eb1-46ac217a77c0.png)

When I type something, the value changes to my typed input, but then quickly flickers back to the pasted value.
![image](https://user-images.githubusercontent.com/17548904/65654119-44eb8c00-e04a-11e9-833f-e8435ec81831.png)

**Comment by psjsaravana** [comment]
+1

**Comment by dsznajder** [comment]
@quanle1994 thanks for issue, I will look into it on next week. However, otp will copy value by it self if copied text has same length as OTP.

**Comment by quanle1994** [comment]
@dsznajder Thank you for your prompt reply :)

**Comment by dsznajder** [comment]
@quanle1994 @mohsinulhaq checkout [v4](https://github.com/dsznajder/react-native-otp-inputs/releases/tag/v4.0.0-alpha.0). It's released now, with some changes related to android bugs.
