### ISSUE TITLE
First input box takes 2 characters when editing.

### ISSUE THREAD

**Issue by quanle1994** [dsznajder/react-native-otp-inputs#134]
When user edits the OTP, for the first box, user can input 2 characters if the text is not selected. Below is the screenshot of the first box having 2 characters instead of 1.
![image](https://user-images.githubusercontent.com/17548904/65654826-af053080-e04c-11e9-87bf-7457468ceeb3.png)

**Comment by dsznajder** [comment]
Duplicated #115
