### ISSUE TITLE
Text colour property is not customisable.

### ISSUE THREAD

**Issue by ashwanihundwani** [dsznajder/react-native-otp-inputs#15]
Can you guys make TextInput colour property customsable, as in my case I need to have black colour for text.

**Comment by AnchalMulchandani** [comment]
hello @ashwanihundwani ,

do you get any solution to change the text color?

**Comment by ashwanihundwani** [comment]
@AnchalMulchandani  No, I am using my own custom solution, as I am constrained on time.

**Comment by AnchalMulchandani** [comment]
@ashwanihundwani 
I have checked for this and got the solution..
You can pass `inputStyles` prop for that one.

**Comment by ashwanihundwani** [comment]
@AnchalMulchandani Thanks Anchal. I can pass in {"color": "#fff"} something like this right?

**Comment by AnchalMulchandani** [comment]
@ashwanihundwani  Yes,You can pass the style under that prop and also using style object-

For eg:-
 1. using style object-

<OtpInputs handleChange={code => console.log(code)} numberOfInputs={6} **inputStyles={styles.otpInputText}** inputsContainerStyles={styles.otpContainerView} inputContainerStyles={styles.inputContainerView}/>

2. Inside prop-
 <OtpInputs handleChange={code => console.log(code)} numberOfInputs={6} **inputStyles={{
"color": "#fff"}}** inputsContainerStyles={styles.otpContainerView} inputContainerStyles={styles.inputContainerView}/>

**Comment by ashwanihundwani** [comment]
@AnchalMulchandani Thanks Anchal, much appreciated.

**Comment by dsznajder** [comment]
I think I can close it as you can customize pretty much everything :)
