### ISSUE TITLE
handleChange function is not being called.

### ISSUE THREAD

**Issue by quanle1994** [dsznajder/react-native-otp-inputs#164]
Hi @dsznajder
I think there is a regression bug with the handleChange callback function after the recent changes.
Previously, the handleChange function will be triggered after every input change, but now, it is not called even when the full OTP has been entered.
![image](https://user-images.githubusercontent.com/17548904/66729471-38569880-ee7e-11e9-931d-ac52e8f83fc4.png)
In this screenshot, the GO button is not enabled when all the inputs are entered but previously, it was. 
![image](https://user-images.githubusercontent.com/17548904/66729502-6cca5480-ee7e-11e9-8f71-03816add2d3d.png)
When I try to log the changes, nothing was shown.

Version: 4.0.0-alpha.1 and 4.0.0-alpha.2

**Comment by axebelk** [comment]
Same here, So changed to some other Package

**Comment by dsznajder** [comment]
@quanle1994 @axebelk In few minutes I will release newest alpha, please checkout if everything works for you :)

**Comment by dsznajder** [comment]
Now it should be called properly. Checkout `react-native-otp-inputs@next`

**Comment by axebelk** [comment]
Still not working properly.. have lot of bugs

**Comment by dsznajder** [comment]
@axebelk could you share your code and version which you use? Are you sure you have installed `4.0.0-alpha.4` version?

**Comment by axebelk** [comment]
I am sure I have installed alpha-4 
    "react-native-keyevent": "^0.2.2",
    "react-native-otp-inputs": "^4.0.0-alpha.4",
and my code is 

<OtpInputs 
                  keyboardType="number-pad"
                  handleTextChange={code => console.log(code)} 
                  selectTextOnFocus={false}
                  numberOfInputs={6} />

When i starting to type it stay on first input box.

**Comment by dsznajder** [comment]
@axebelk iOS or Android? Also, did you setup properly `react-native-keyevent` for android?
