### ISSUE TITLE
Update README unfocusedBorderColor capitalization to unFocusedBorderColor

### ISSUE THREAD

**Issue by jannainm** [dsznajder/react-native-otp-inputs#17]
This tripped me up for a little while. The readme has the incorrect capitalization  of the `unFocusedBorderColor` prop listed as `un**f**ocusedBorderColor`.

If you would like I can fork and submit a PR for this change or you can push it in your next update. Let me know what works for you - great work on this component 🥇

**Comment by dsznajder** [comment]
@jannainm I will release fix today, as I'm working on documenting types also :)

**Comment by dsznajder** [comment]
Fixed in 2.0.1
