### ISSUE TITLE
How focus inputs ? 

### ISSUE THREAD

**Issue by arshidkv12** [dsznajder/react-native-otp-inputs#171]
How to focus?

**Comment by dsznajder** [comment]
@arshidkv12 What would you like to focus? Some specific input or just first?

**Comment by arshidkv12** [comment]
Just first...
I resolved by using private focus internal function.

Version 3.3.2

**Comment by dsznajder** [comment]
@arshidkv12 checkout `react-native-otp-input@next`. I've added `focus` method for this :)

**Comment by codeamo** [comment]
Hi there, just wondering this issue of focusing was solved. I mean, my issue is that I have set the autoFocus on and I want it to automatically focus on the beginning of OTP input but by default, it's focusing on random inputs mostly on the second last inputs. How can I autoFocus on the first OTP input my default? 

I have seen on the example code that you have used a focusOTP function which you then call the function as a button press but how can you make it automatically so you don't have to press the button to fix the focus. 

Thanks

**Comment by dsznajder** [comment]
@codeamo You can do exactly same function call but on componentDidMount.

**Comment by codeamo** [comment]
@dsznajder since I am using react hooks, I have done the same things with useEffect but still not working the first render but the second render. any help?
my code is here: 
`
const focusOTP = () => {
    otpRef.current.focus();
  };

  useEffect(() => {
    focusOTP();
  }, []);

<OtpInputs
          ref={otpRef}
          keyboardType="number-pad"
          handleChange={num => setCode({ code: num })}
          numberOfInputs={4}
          autoFocus
        />
`

**Comment by dsznajder** [comment]
Remove autoFocus prop, and give it a try

**Comment by codeamo** [comment]
Yep, that works, Does the package provide a call back function that fires after the input fields are full?

Thanks

**Comment by dsznajder** [comment]
@codeamo No, you can do this through `handleChange` function.
