### ISSUE TITLE
Set value

### ISSUE THREAD

**Issue by mayankpandav** [dsznajder/react-native-otp-inputs#172]
im not able to set detected OTP because of handlechange...

**Comment by dsznajder** [comment]
@mayankpandav Which version and what your code looks like?

**Comment by mayankpandav** [comment]
I'm using latest version there is no field like value to put value instead we have handlechange which are handling onchange and value

**Comment by dsznajder** [comment]
@mayankpandav There is no possibility, for now. I will include this in v4 :)

**Comment by mayankpandav** [comment]
@dsznajder  Thank you for your time

**Comment by augustosamame** [comment]
+1 for this feature. I need to clear any inputted OTP if Resend button is clicked, but it's currently impossible.

**Comment by mayankpandav** [comment]
@augustosamame  it will work if they put value of input, on resend we can clear state what we have putted as a value.. just need to add value,  if you are in hurry then you can do fork and put some changes....

**Comment by dsznajder** [comment]
@augustosamame There is `reset` method on `OtpInputs` instance. I've added `defaultValue` in current version.

**Comment by mayankpandav** [comment]
@dsznajder thank you....
