### ISSUE TITLE
Error: while trying ro resolve modules `react-native-otp-inputs`

### ISSUE THREAD

**Issue by arisupriatna14** [dsznajder/react-native-otp-inputs#18]
Hallo guys, can you help me?

error: bundling failed: Error: While trying to resolve module react-native-otp-inputs from file /Users/useradmin/Documents/xxx-app-consumer/app/components/RegisterOtp/RegisterOtp.screen.js, the package /Users/useradmin/Documents/xxx-app-consumer/node_modules/react-native-otp-inputs/package.json was successfully found. However, this package itself specifies a main module field that could not be resolved (/Users/useradmin/Documents/xxx-app-consumer/node_modules/react-native-otp-inputs/lib/index.tsx. Indeed, none of these files exist:

I using react native version 0.54.4
I have tried to delete the modules node, clear Watchman, but still it can't. I read in the documentation, can support react native versio >= 0.53.0

**Comment by arisupriatna14** [comment]
Hallo guys, can you help me?

error: bundling failed: Error: While trying to resolve module `react-native-otp-inputs` from file `/Users/useradmin/Documents/boost-app-consumer/app/components/RegisterOtp/RegisterOtp.screen.js`, the package `/Users/useradmin/Documents/boost-app-consumer/node_modules/react-native-otp-inputs/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/useradmin/Documents/boost-app-consumer/node_modules/react-native-otp-inputs/lib/index.tsx`. Indeed, none of these files exist:

 I using react native version 0.54.4
I have tried to delete the modules node, clear Watchman, but still it can't. I read in the documentation, can support react native versio> = 0.53.0

**Comment by dsznajder** [comment]
@arisupriatna14 Thanks for reporting the issue. I could not reproduce this one by my self. Could you provide some reproduction?

**Comment by dsznajder** [comment]
@arisupriatna14 I've created a Snack here and it seems to be fine. https://snack.expo.io/Hkg1KgkiV

**Comment by dsznajder** [comment]
@arisupriatna14 I've updated documentation. It seems that there are some breaking changes on newer versions of `react-native`. I run it on version 0.57 or higher, so I've added it to documentation.
