### ISSUE TITLE
Hello, when ios is running, when I delete all the Numbers and add them again, the Numbers will be hidden. What should I do?

### ISSUE THREAD

**Issue by L-Mno** [dsznajder/react-native-otp-inputs#2]
Hello, I have run your example, everything is ok on Android, but there was a problem in Ios. The number that was selected before deleted will not be displayed. If this component is still maintained, I hope it can be solved.

**Comment by dsznajder** [comment]
I will look into it and get back with feedback today @L-Mno :)

**Comment by L-Mno** [comment]
react-native  --version 0.54.2

First of all,    npm i react-native-otp-inputs --save

The following

![b84de294-3bb2-42ac-a210-894f8751fd20](https://user-images.githubusercontent.com/35682188/44299233-a52add00-a324-11e8-8d01-dbde0a19d4bc.png)

Everything was fine the first time I typed, but when I deleted the Numbers and rechose the other Numbers, it looked like this.

![2771020d-7af4-43a6-b6c9-4b1dc68495cf](https://user-images.githubusercontent.com/35682188/44299207-3483c080-a324-11e8-8bb0-4145740069f9.png)

It only displays a number in front of the focus, hoping to help solve the problem. 

Thanks for your quick reply!

**Comment by dsznajder** [comment]
Try to update to the newest version, should be resolved with `0.6.1`

**Comment by L-Mno** [comment]
You can close this error, You can also optimize   ##this.

![f5c5f227-bc0b-41c2-8d76-d821a3990dc8](https://user-images.githubusercontent.com/35682188/44375564-e8549e00-a526-11e8-952a-8a4db0abb909.png)

When you select a number on ios, you can select it in a more beautiful way, and hopefully this component will do better.

**Comment by dsznajder** [comment]
@L-Mno You can try to set `selectTextOnFocus` to false.
