### ISSUE TITLE
Wrong otp autofill.

### ISSUE THREAD

**Issue by rmamtaventures** [dsznajder/react-native-otp-inputs#200]

**Comment by dsznajder** [comment]
@rmamtaventures Could you explain what do you mean by `Wrong otp autofill`? Some code reproduction or example.

**Comment by rmamtaventures** [comment]
Current behaviour:- When navigate to otp screen, it's autofill by second last message of otp from device messages.
Expected behaviour:- It should be autofill by latest otp message from device messages.

Is it clear?

**Comment by dsznajder** [comment]
@rmamtaventures It's autofilled with copied text in `Clipboard` so behaviour is correct.

**Comment by rmamtaventures** [comment]
Each time it's autofill with same otp in android device. I have not copied any otp.

**Comment by dsznajder** [comment]
@rmamtaventures Please share example. I cannot help without any context :)

**Comment by mayankpandav** [comment]
@dsznajder its happen when you have copied value exact same as OTP require ....

**Comment by paras-kc** [comment]
facing the same issue. can anyone help please??

**Comment by mayankpandav** [comment]
@paras-kc you can do fork and do your code...

**Comment by dsznajder** [comment]
@mayankpandav you can also open a PR that fixes/resolve this. I did not receive any of the requested things as reproduction or code example. Also, couldn't reproduce it by myself 😕

**Comment by Taiyab123** [comment]
@dsznajder if any text is already copied in the clipboard and now send OTP and redirect to OTP screen to input OTP but that copied text is showing there. Also unable to edit or clear the input. Can anyone help, please?

**Comment by dsznajder** [comment]
@Taiyab123 could you provide some reproduction?

**Comment by Taiyab123** [comment]
1. First copy some text on clipboard,
2. in app move to otp screen you will see that otp is auto filled
3.  you will not  be able to edit.

Thank you

**Comment by SiddharthRana** [comment]
Hi, getting the same issue. I want to disable the autofill, how can i do it?

**Comment by dsznajder** [comment]
It seems to be working fine in `5.0.0-alpha.0`. Today I will try to release stable v5.
