### ISSUE TITLE
Keyevent doesn't fire if Samsung keyboard is used (Google keyboard works perfectly)

### ISSUE THREAD

**Issue by ianidi** [dsznajder/react-native-otp-inputs#213]
I am not sure if it is related to otp inputs. I will open an issue in keyevents repository. Please see the video. At first I was using the google keyboard and everything worked perfectly. Then I switch to Samsung keyboard and it doesn't work at all.

https://yadi.sk/i/UuAFWwYjfZIsgQ

**Comment by dsznajder** [comment]
[Related issue](https://github.com/kevinejohn/react-native-keyevent/issues/43)

**Comment by dsznajder** [comment]
@ianidi Thanks for the detailed issue. I find out that the problem lays inside React-Native. When you change keyboardType to `phone-pad` it will work fine.
Unfortunately, I can't do anything other than just restrict keyboard types.

**Comment by rusliabdulgani** [comment]
already add keyboardType='phone-pad' but still not working in some android phone, but work well on some android phone. 
it's still issue of samsung keyboard?

**Comment by dsznajder** [comment]
@rusliabdulgani Yes it is. We had the same issue on our production and now it seems working fine. Did you updated package to newest version?
