### ISSUE TITLE
OTP not auto-populating correctly in IOS

### ISSUE THREAD

**Issue by chakkizza** [dsznajder/react-native-otp-inputs#221]
Hello Team, 
Thank You for this fantastic module. I am using version: 3.3.1. Recently, I found that on IOS, the OTP is not getting auto-populated correctly. Earlier it used to.

Nothing was really changed from our side in the app as such.

The detailed issue is as described:
1] The otp message is received
2] IPhone displays correct OTP on top of the keyboard
3] When clicked on it, it only populates the first digit and rest 3 are blank.

Few days back, it used to populate all four digits correctly.

On Android, when the otp comes and we click on the copy otp button in some devices, it populates correctly.

Please advice on the same.

**Comment by dsznajder** [comment]
@chakkizza Sorry for problem! I've restored this iOS functionality in `v4.1.0` :) If there will be any issues related to this just open separate issue :)
