### ISSUE TITLE
can you please tell how to diable otp auto fill it is always filling wrong otp input

### ISSUE THREAD

**Issue by paras-kc** [dsznajder/react-native-otp-inputs#222]

**Comment by dsznajder** [comment]
@paras-kc It should be possible to pass some prop probably. More likely feature request :) Looks like good first issue.

**Comment by dsznajder** [comment]
@paras-kc I've added v4.1.0 `autofillFromClipboard` prop which is default to `true`. You can just pass `false` and autofilling will be skipped. In addition, I'm still not able to reproduce your issue without any code example unfortunately 😢.
