### ISSUE TITLE
secureTextEntry not working in Android

### ISSUE THREAD

**Issue by AnchalMulchandani** [dsznajder/react-native-otp-inputs#23]
I have added this component and working fine in iOS but in android "secureTextEntry" is not working.

Any idea how it will work?

**Comment by dsznajder** [comment]
@AnchalMulchandani Hi, It's not really related to my package but to React-Native
https://github.com/facebook/react-native/issues/20606. I will leave it as reference to this issue.

**Comment by AnchalMulchandani** [comment]
@dsznajder  I want to secure the code in android also but its not working with "secureTextEntry".

AnyIdea how to get inputs in dot formate(secured formate) instead of number formate?

**Comment by AnchalMulchandani** [comment]
@dsznajder  I got the solution Thanks!

Its all about, "secureTextEntry" will not work with keyboardType={"email-address"} or keyboardType={"phone-pad"} and in package its by-default {"phone-pad"}, so it was not working..

I passed keyboardType={"numeric"}  and it works :) 

Thanks

**Comment by Abhishekgarg727** [comment]
> @dsznajder I got the solution Thanks!
> 
> Its all about, "secureTextEntry" will not work with keyboardType={"email-address"} or keyboardType={"phone-pad"} and in package its by-default {"phone-pad"}, so it was not working..
> 
> I passed keyboardType={"numeric"} and it works :)
> 
> Thanks

where did you add prop` KeyboardType={"numeric"}` , please a code snippet if possible

**Comment by AnchalMulchandani** [comment]
> > @dsznajder I got the solution Thanks!
> > Its all about, "secureTextEntry" will not work with keyboardType={"email-address"} or keyboardType={"phone-pad"} and in package its by-default {"phone-pad"}, so it was not working..
> > I passed keyboardType={"numeric"} and it works :)
> > Thanks
> 
> where did you add prop` KeyboardType={"numeric"}` , please a code snippet if possible



Here is the way  i have used-

    <OtpInputs
                                    isReset={isReset}
                                    clearTextOnFocus={true}
                                    handleChange={code => this.changeValue('OTP', code)}
                                    numberOfInputs={4}
                                    keyboardType={"numeric"} secureTextEntry ={true}
                                    
                                />


i just overwrite its keyboardtype property, as bydefault it's value is 'phone-pad'.

**Comment by Akshayshakya** [comment]
> @dsznajder I got the solution Thanks!
> 
> Its all about, "secureTextEntry" will not work with keyboardType={"email-address"} or keyboardType={"phone-pad"} and in package its by-default {"phone-pad"}, so it was not working..
> 
> I passed keyboardType={"numeric"} and it works :)
> 
> Thanks

Thank you so much its perfect answer.
