### ISSUE TITLE
react-native-keyevent not work in custom installed keyboard 

### ISSUE THREAD

**Issue by rusliabdulgani** [dsznajder/react-native-otp-inputs#235]
Dear All,

I found issue on custom installed keyboard for react-native-keyevent. it not work at all. 
Is possible to get data input if react-native-keyevent not work? cause if i get console of otp input, i'm not get data if react-native-keyevent not work properly.

**Comment by dsznajder** [comment]
@rusliabdulgani There is huge possibility with that, but look on origininal issue #213 This can be caused because of custom `keyboardType`, and this issue lives inside RN (AFAIK 🤔 )

**Comment by dsznajder** [comment]
@rusliabdulgani Could you please check `@next` channel if everything works for you? We've removed `react-native-keyevent` as it wasn't really reliable for custom keyboards.

**Comment by dsznajder** [comment]
@rusliabdulgani closing as it's fixed on `@next` route.
