### ISSUE TITLE
iOS textContentType=oneTimeCode autofilling the entire OTP code at first index

### ISSUE THREAD

**Issue by sivakumar-cf** [dsznajder/react-native-otp-inputs#239]
Hi, I am facing an issue In iOS OTP code auto-filling.

I have set 6 as `numberOfInputs` and when I got OTP code SMS from keyboard accessory view. 
While Tapping on it, the entire OTP code of 6 letters got filled to the first index of TextInput out of 6.  The rest of TextInputs remains empty.
![IMG_2183](https://user-images.githubusercontent.com/22584937/75417141-451fe880-5956-11ea-8518-550d26e9a327.png)
![IMG_2184](https://user-images.githubusercontent.com/22584937/75417150-48b36f80-5956-11ea-802f-094856bc01ec.png)

**Comment by dsznajder** [comment]
@sivakumar-cf Hi! Could you provide version which you use? In addition, try `5.0.0-alpha.0`.

**Comment by sivakumar-cf** [comment]
Yes I am using the latest version `^5.0.0-alpha.0`

**Comment by dsznajder** [comment]
@sivakumar-cf I will take a look at this.

**Comment by sivakumar-cf** [comment]
Thanks it worked.
