### ISSUE TITLE
autoFocus

### ISSUE THREAD

**Issue by dpatil2011** [dsznajder/react-native-otp-inputs#247]
if we give  autoFocus={true} it is focusing to last index instead of first index.

**Comment by dsznajder** [comment]
@dpatil2011 Because you should not use `autoFocus` prop. Instead, use `focus` method on `OtpInputs` ref.

**Comment by dpatil2011** [comment]
> @dpatil2011 Because you should not use `autoFocus` prop. Instead, use `focus` method on `OtpInputs` ref.

Thank you
