### ISSUE TITLE
Not focusing to next input in android

### ISSUE THREAD

**Issue by rahulje9** [dsznajder/react-native-otp-inputs#249]
I have an issue with the input in android, If I fill in the fields and then try to re-enter the same digit in the input filed. it is not focusing on to the next input field. In ios it is getting focused to the next input, the issue is only in android. Please find the attached gif for reference.

I'm on 
`react-native - 0.63.2`
`react - 16.13.1`
`react-native-otp-inputs- 6.0.0` 

```
<OtpInputs
   handleChange={(code) => this._onChange(code)}
   numberOfInputs={5}
   autofillFromClipboard={false}
   style={styles.otpContainerView}
   inputContainerStyles={styles.otpInputContainerView}
   inputStyles={styles.otpInputStyles}
   />
```

![screenrecord](https://user-images.githubusercontent.com/22475675/96078956-3f6d1800-0ed1-11eb-8eca-620aba2c5ecb.gif)

please let me know if anything else is needed from my side.

**Comment by dsznajder** [comment]
@rahulje9 Unfortunately with current implementation of react-native TextInput events, you can't do any action as it does not trigger any event when you pass same text. Maybe something changed but it need a check. As "workaround" I recommend reset inputs on send.

**Comment by rahulje9** [comment]
@dsznajder is this a limitation in the Android side? how to reset inputs on send?

**Comment by dsznajder** [comment]
@rahulje9 [In documentation](https://github.com/dsznajder/react-native-otp-inputs/blob/master/docs/API.md#methods) you can find method which can be called on ref.
