### ISSUE TITLE
Infinite pasting from clipboard

### ISSUE THREAD

**Issue by BayCo** [dsznajder/react-native-otp-inputs#250]
Simulator: ios 14
there is infinite pasting from clipboard, on component load

**Comment by dsznajder** [comment]
@BayCo Ahh my bad, I forgot to handle `ios` 14, but you can just pass autofillFromClipboard={false} when needed :)

**Comment by BayCo** [comment]
Cool, i'll be waiting

**Comment by nguyenductoan1995** [comment]
The problem has been fixed yet, everyone
