### ISSUE TITLE
One time code autofilling weird behaviour 

### ISSUE THREAD

**Issue by yudiz-vipul** [dsznajder/react-native-otp-inputs#253]
I am getting weird behavior filling code using the autofill option, I don't want auto-filling features to avoid the weird issues. Please check the attachment.

![RPReplay_Final1611745035](https://user-images.githubusercontent.com/45070224/105982850-df843100-60bd-11eb-9421-51b97b650c46.gif)

Also, you can check my code snippet here:
`<OtpInputs
    ref={otpInputsRef}
    selectionColor={Platform.OS === 'ios' && AppColors.app490074}
    inputContainerStyles={styles.otpInput}
    inputStyles={styles.otpInputText}
    numberOfInputs={6}
    autofillFromClipboard={false}
    returnKeyType={'done'}
    handleChange={(code) => {setOTPVerificationCode(code)}}
/>
`

**Comment by dsznajder** [comment]
@yudiz-vipul please check on the production code, as it may be caused by many things in development. It also looks like you have some code that is not optimized.
