### ISSUE TITLE
Button colour changing after filling the inputs

### ISSUE THREAD

**Issue by vinaynarayankutty** [dsznajder/react-native-otp-inputs#254]
After filling in the otp code, the colour of the button after otpInputs component changes. I have no idea why it is showing this weird behaviour. 

Please find the attached screenshot for detailed view. Here you can see a greyish background colour around the continue button. I've added any backgroundcolor to touchable opacity but it is still showing.
<img width="917" alt="Screenshot 2021-02-24 at 3 13 06 PM" src="https://user-images.githubusercontent.com/40576238/108981722-03359980-76b3-11eb-9451-7daa2e7fe246.png">

**Comment by dsznajder** [comment]
@vinaynarayankutty It's not package-related issue. Also, I'm not seeing any `backgroundColor` here, more like `borderColor`.

**Comment by vinaynarayankutty** [comment]
@dsznajder Hi, see the problem is I've given the whole background a white color. See the touchable opacity I've given any grey color and of you look at the simulator screen you can see a grey color around the continue button. Please find the attached screenshots for clarity.
<img width="877" alt="Screenshot 2021-02-24 at 4 02 43 PM" src="https://user-images.githubusercontent.com/40576238/108987963-e8b2ee80-76b9-11eb-9d46-da559f901b09.png">
<img width="877" alt="Screenshot 2021-02-24 at 4 03 01 PM" src="https://user-images.githubusercontent.com/40576238/108987978-ed77a280-76b9-11eb-9528-fb933d227b3c.png">
<img width="888" alt="Screenshot 2021-02-24 at 4 03 18 PM" src="https://user-images.githubusercontent.com/40576238/108987982-eea8cf80-76b9-11eb-9381-902fb00e9fdd.png">

**Comment by dsznajder** [comment]
@vinaynarayankutty It's still not related to the package, as it's just `TextInput`'s components, I have no idea what is actually happening here, but it's related more to React-Native. It's just in "selected" state. Check on a real device.
