### ISSUE TITLE
Expo has a Clipboard API

### ISSUE THREAD

**Issue by Hirbod** [dsznajder/react-native-otp-inputs#274]
https://docs.expo.dev/versions/latest/sdk/clipboard/

And since it is easy installable outside of Expo (https://github.com/expo/expo/tree/master/packages/expo-clipboard) it should be used as the main library for broad user support.

**Comment by dsznajder** [comment]
@Hirbod I disagree. Expo forces you to use it on your project and integrate it with the rest of `expo-modules` stuff. It also has half of the main clipboard package installs. If the integration does not need `expo`, installation is similar to main package.

**Comment by dsznajder** [comment]
@Hirbod I'm happy to merge PR if it would support both approaches.

**Comment by crieggalder** [comment]
Hey @chillios-ts - @hirbod is right. Expo clipboard works great with or without Expo, so it's the best solution. And luckily it's a drop-in replacement! `Clipboard.setString()` is the same, and `Clipboard.getString()` becomes `Clipboard.getStringAsync()`.

I'd PR it but looks like there are already some pending PRs. If you're still maintaining this, would you consider just swapping the deps? Should be 3 lines of changed code total.
