### ISSUE TITLE
Not able to change input text color in normal mode. It's always white.

### ISSUE THREAD

**Issue by NazifaNajish01** [dsznajder/react-native-otp-inputs#3]
We have option to set '**inputTextErrorColor**' but not any option for '**inputTextColor**'. It's always white.
Please add support for input text color as well.

**Comment by dsznajder** [comment]
I will implement this later today :)

**Comment by dsznajder** [comment]
@NazifaNajish01 You can pass `inputStyles` prop for that one

**Comment by NazifaNajish01** [comment]
Thanks, Damian Sznajder! It's really helpful. ☺
Appreciate your efforts. 👏

Regards,
Nazifa Najish

**Comment by graphee-gabriel** [comment]
Hello, 

Could you add it to the docs ? Struggled 30mn to find it eventually in the code :-p.

Thanks for a great lib

**Comment by dsznajder** [comment]
@graphee-gabriel 	Sorry, I thought I've added this. I added it in docs, also I've linked to the default styles.

**Comment by graphee-gabriel** [comment]
No problem, thank you :-)
