### ISSUE TITLE
for twice validate, need clear function to call

### ISSUE THREAD

**Issue by codecomeon** [dsznajder/react-native-otp-inputs#31]
password twice validate, like this:
`this.otpInputComponent.clear();`

**Comment by dsznajder** [comment]
You can't clear the otp code? I'm pretty sure if you change "value" to an empty string, inputs should be cleared.

**Comment by mohmdalfaha** [comment]
@dsznajder How do I clear the inputs on entering wrong code ??
Could you please show some code

**Comment by dsznajder** [comment]
@codecomeon @mohmdalfaha Ok, sorry I mislead you. I didn't realise that package does not expose this mechanism. I will update it when I find time. Probably this week :)

**Comment by dsznajder** [comment]
@codecomeon @mohmdalfaha I've added method `clear` with documentation. 
Look in README.md and update to `v3.3.1`! :)
