### ISSUE TITLE
No support for alpha numeric input. Keyboard type is always number values only.

### ISSUE THREAD

**Issue by NazifaNajish01** [dsznajder/react-native-otp-inputs#4]
By default keyboard type is 'Phone-pad' (numbers) only. But, for alpha-numeric (letters+numbers) OTP  not able to use the react-native-otp-input.

**Comment by dsznajder** [comment]
I will implement this later today :)

**Comment by dsznajder** [comment]
@NazifaNajish01 Published in `v0.7.0`

**Comment by NazifaNajish01** [comment]
Thanks, Damian Sznajder! It's really helpful. ☺
Appreciate your efforts. 👏

Regards,
Nazifa Najish
