### ISSUE TITLE
Auto capitalization problem for keyboard type 'default'/alphanumeric values

### ISSUE THREAD

**Issue by NazifaNajish01** [dsznajder/react-native-otp-inputs#5]
For the OTP which contains small letters in it for e.g. **a1b2c3** or **abcde** ,

According to the default behavior autoCapitalize:'sentences' (i.e first letter of each sentence in caps), the keyboard caps lock gets on for each **TextInput** of the 'react-native-otp-inputs' which is a bit annoying for users if they have an alphanumeric OTP.

Can there be an option to set auto capitalization "**none**" (or other) by an open prop similar to  'keyboardType'?

**Comment by dsznajder** [comment]
Sure, I will implement this today or tomorrow. You can also send a PR if you need something specific :)

**Comment by dsznajder** [comment]
Check 1.0.0 v
