### ISSUE TITLE
LTR support?

### ISSUE THREAD

**Issue by vish2595** [dsznajder/react-native-otp-inputs#69]

**Comment by Rohithzr** [comment]
@dsznajder I am from @vish2595 team, I am forking the library to add LTR support.

Issue Description: If RTL is enabled at the device level or the application level, the OTP boxes generated by the libarary get reversed, meanining the first box has the id 3 (if otp length is 4). Whereas the numbers in RTL must still be in LTR order. to support this I propose to add a `forceLTR` option that would calculate the IDs in reverse order.

**Comment by dsznajder** [comment]
@Rohithzr Thanks! If I can help you with something just give me a shout!
