### ISSUE TITLE
Passing value to auto fill otp

### ISSUE THREAD

**Issue by ShekharD175** [dsznajder/react-native-otp-inputs#8]
How to achieve auto fill OTP

**Comment by dsznajder** [comment]
Unfortunately, current implementation does not have this feature. I also never done something like autofill feature, if you have some experience could you provide some examples? 
@ShekharD175

**Comment by dsznajder** [comment]
Released in v2.0.0

**Comment by yagnesh-y** [comment]
@dsznajder Sorry but can't find usage related to this? The only thing i find is the defaultValue?
